{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a5efa5b5",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.\n",
      "  PendingDeprecationWarning\n",
      "/home/michael/Desktop/flow/flow/utils/flow_warnings.py:26: PendingDeprecationWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.\n",
      "  PendingDeprecationWarning\n",
      "{'num_workers': 5, 'num_envs_per_worker': 1, 'create_env_on_driver': False, 'rollout_fragment_length': 200, 'batch_mode': 'truncate_episodes', 'gamma': 0.999, 'lr': 5e-05, 'train_batch_size': 3750, 'model': {'_use_default_native_models': False, 'fcnet_hiddens': [256, 256], 'fcnet_activation': 'tanh', 'conv_filters': [[16, [8, 8], 4], [32, [4, 4], 2], [256, [11, 11], 1]], 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': False, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'num_framestacks': 'auto', 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1, 'framestack': True}, 'optimizer': {}, 'horizon': 750, 'soft_horizon': False, 'no_done_at_end': False, 'env': None, 'observation_space': None, 'action_space': None, 'env_config': {}, 'env_task_fn': None, 'render_env': False, 'record_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'preprocessor_pref': 'deepmind', 'log_level': 'WARN', 'callbacks': <class 'ray.rllib.agents.callbacks.DefaultCallbacks'>, 'ignore_worker_failures': False, 'log_sys_usage': True, 'fake_sampler': False, 'framework': 'torch', 'eager_tracing': False, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'evaluation_interval': None, 'evaluation_num_episodes': 10, 'evaluation_parallel_to_training': False, 'in_evaluation': False, 'evaluation_config': {}, 'evaluation_num_workers': 0, 'custom_eval_function': None, 'sample_async': False, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'compress_observations': False, 'collect_metrics_timeout': 180, 'metrics_smoothing_episodes': 100, 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'min_iter_time_s': 0, 'timesteps_per_iteration': 0, 'seed': None, 'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, '_fake_gpus': False, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, 'custom_resources_per_worker': {}, 'num_cpus_for_driver': 1, 'placement_strategy': 'PACK', 'input': 'sampler', 'input_config': {}, 'actions_in_input_normalized': False, 'input_evaluation': ['is', 'wis'], 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'multiagent': {'policies': {}, 'policy_mapping_fn': None, 'policies_to_train': None, 'observation_fn': None, 'replay_mode': 'independent', 'count_steps_by': 'env_steps'}, 'logger_config': None, 'simple_optimizer': -1, 'monitor': -1, 'use_critic': True, 'use_gae': True, 'lambda': 0.97, 'kl_coeff': 0.2, 'sgd_minibatch_size': 128, 'shuffle_sequences': True, 'num_sgd_iter': 10, 'lr_schedule': None, 'vf_loss_coeff': 1.0, 'entropy_coeff': 0.0, 'entropy_coeff_schedule': None, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'grad_clip': None, 'kl_target': 0.02, 'vf_share_layers': -1}\n",
      "2022-10-09 14:21:18,970\tINFO services.py:1247 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "2022-10-09 14:21:19,752\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "== Status ==\n",
      "Memory usage on this node: 3.3/31.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 0/6 CPUs, 0/6 GPUs, 0.0/11.5 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)\n",
      "Result logdir: /home/michael/ray_results/merge_0\n",
      "Number of trials: 1/1 (1 PENDING)\n",
      "+-------------------------------+----------+-------+\n",
      "| Trial name                    | status   | loc   |\n",
      "|-------------------------------+----------+-------|\n",
      "| PPO_MergePOEnv-v0_8d984_00000 | PENDING  |       |\n",
      "+-------------------------------+----------+-------+\n",
      "\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=2944)\u001b[0m 2022-10-09 14:21:21,078\tWARNING ppo.py:143 -- `train_batch_size` (3750) cannot be achieved with your other settings (num_workers=5 num_envs_per_worker=1 rollout_fragment_length=200)! Auto-adjusting `rollout_fragment_length` to 750.\n",
      "\u001b[2m\u001b[36m(pid=2944)\u001b[0m 2022-10-09 14:21:21,078\tINFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "2022-10-09 14:21:21,601\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "2022-10-09 14:21:23,414\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=2944)\u001b[0m 2022-10-09 14:21:23,840\tWARNING util.py:55 -- Install gputil for GPU system monitoring.\n",
      "2022-10-09 14:21:25,181\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.7' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=45.00.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.7' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=45.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.25' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=81.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_20.2' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=82.00.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.25' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=81.00.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.25' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=81.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.26' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=81.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_20.2' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=82.50.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.43' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=117.00.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.45' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=118.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.63' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=153.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.59' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=153.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.76' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=189.00.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.74' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=189.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.117' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=261.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.134' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=297.00.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.126' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=297.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.171' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=369.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_20.10' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=370.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.171' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=369.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_20.10' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=370.50.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-10-09 14:21:27,093\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.158' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=369.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.176' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=405.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.225' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=477.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.225' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=477.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_20.13' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=478.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.261' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=549.50.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.209' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=477.00.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.279' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=585.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.297' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=621.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_20.17' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=623.00.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.279' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=585.50.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_10.27' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=549.00.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.297' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=621.00.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.315' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=657.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.351' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=729.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.260' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=585.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_20.16' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=586.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_00.350' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=729.50.\n",
      "\u001b[2m\u001b[36m(pid=2945)\u001b[0m Warning: Vehicle 'flow_20.20' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=730.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.276' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=621.00.\n",
      "2022-10-09 14:21:28,984\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.289' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=657.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.308' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=693.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.325' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=729.00.\n",
      "2022-10-09 14:21:30,730\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-10-09 14:21:32,508\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "Result for PPO_MergePOEnv-v0_8d984_00000:\n",
      "  agent_timesteps_total: 3750\n",
      "  custom_metrics: {}\n",
      "  date: 2022-10-09_14-21-33\n",
      "  done: false\n",
      "  episode_len_mean: 750.0\n",
      "  episode_media: {}\n",
      "  episode_reward_max: 592.9287458448014\n",
      "  episode_reward_mean: 480.5749087949997\n",
      "  episode_reward_min: 401.4027530445808\n",
      "  episodes_this_iter: 5\n",
      "  episodes_total: 5\n",
      "  experiment_id: 4776d3b2ff4f40898ddeae702eab05a8\n",
      "  hostname: michael-villarreal\n",
      "  info:\n",
      "    learner:\n",
      "      default_policy:\n",
      "        custom_metrics: {}\n",
      "        learner_stats:\n",
      "          allreduce_latency: 0.0\n",
      "          cur_kl_coeff: 0.19999999999999998\n",
      "          cur_lr: 5.000000000000001e-05\n",
      "          entropy: 7.093719358444214\n",
      "          entropy_coeff: 0.0\n",
      "          kl: 0.002813184208318565\n",
      "          policy_loss: -0.0013878190567872177\n",
      "          total_loss: 406.4865391031901\n",
      "          vf_explained_var: 7.947286162490741e-10\n",
      "          vf_loss: 406.48736267089845\n",
      "        model: {}\n",
      "    num_agent_steps_sampled: 3750\n",
      "    num_steps_sampled: 3750\n",
      "    num_steps_trained: 3750\n",
      "  iterations_since_restore: 1\n",
      "  node_ip: 192.168.1.65\n",
      "  num_healthy_workers: 5\n",
      "  off_policy_estimator: {}\n",
      "  perf:\n",
      "    cpu_util_percent: 21.84\n",
      "    ram_util_percent: 14.300000000000004\n",
      "  pid: 2944\n",
      "  policy_reward_max: {}\n",
      "  policy_reward_mean: {}\n",
      "  policy_reward_min: {}\n",
      "  sampler_perf:\n",
      "    mean_action_processing_ms: 0.054580393866121214\n",
      "    mean_env_render_ms: 0.0\n",
      "    mean_env_wait_ms: 6.612788821346115\n",
      "    mean_inference_ms: 0.5624177452727419\n",
      "    mean_raw_obs_processing_ms: 1.4642074168442725\n",
      "  time_since_restore: 9.834136009216309\n",
      "  time_this_iter_s: 9.834136009216309\n",
      "  time_total_s: 9.834136009216309\n",
      "  timers:\n",
      "    learn_throughput: 1313.263\n",
      "    learn_time_ms: 2855.482\n",
      "    sample_throughput: 537.798\n",
      "    sample_time_ms: 6972.881\n",
      "    update_time_ms: 1.405\n",
      "  timestamp: 1665343293\n",
      "  timesteps_since_restore: 0\n",
      "  timesteps_total: 3750\n",
      "  training_iteration: 1\n",
      "  trial_id: 8d984_00000\n",
      "  \n",
      "== Status ==\n",
      "Memory usage on this node: 4.5/31.3 GiB\n",
      "Using FIFO scheduling algorithm.\n",
      "Resources requested: 6.0/6 CPUs, 0/6 GPUs, 0.0/11.5 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)\n",
      "Result logdir: /home/michael/ray_results/merge_0\n",
      "Number of trials: 1/1 (1 RUNNING)\n",
      "+-------------------------------+----------+-------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------+\n",
      "| Trial name                    | status   | loc               |   iter |   total time (s) |   ts |   reward |   episode_reward_max |   episode_reward_min |   episode_len_mean |\n",
      "|-------------------------------+----------+-------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------|\n",
      "| PPO_MergePOEnv-v0_8d984_00000 | RUNNING  | 192.168.1.65:2944 |      1 |          9.83414 | 3750 |  480.575 |              592.929 |              401.403 |                750 |\n",
      "+-------------------------------+----------+-------------------+--------+------------------+------+----------+----------------------+----------------------+--------------------+\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.7' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=45.50.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_20.1' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=47.00.\n",
      "2022-10-09 14:21:34,351\tWARNING worker.py:1189 -- The agent on node michael-villarreal failed with the following error:\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "    loop.run_until_complete(agent.run())\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "    return future.result()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "    modules = self._load_modules()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "    c = cls(self)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "    self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "    namespace=\"ray\", port=metrics_export_port)))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "    options=option, gatherer=option.registry, collector=collector)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "    self.serve_http()\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "    port=self.options.port, addr=str(self.options.address))\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "    TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "    infos = socket.getaddrinfo(address, port)\n",
      "  File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "socket.gaierror: [Errno -2] Name or service not known\n",
      "\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 366, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 354, in <module>\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     loop.run_until_complete(agent.run())\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/asyncio/base_events.py\", line 584, in run_until_complete\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     return future.result()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 144, in run\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     modules = self._load_modules()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/agent.py\", line 98, in _load_modules\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     c = cls(self)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/new_dashboard/modules/reporter/reporter_agent.py\", line 148, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self._metrics_agent = MetricsAgent(dashboard_agent.metrics_export_port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/metrics_agent.py\", line 77, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     namespace=\"ray\", port=metrics_export_port)))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 334, in new_stats_exporter\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     options=option, gatherer=option.registry, collector=collector)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 266, in __init__\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     self.serve_http()\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/ray/_private/prometheus_exporter.py\", line 321, in serve_http\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     port=self.options.port, addr=str(self.options.address))\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 168, in start_wsgi_server\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     TmpServer.address_family, addr = _get_best_family(addr, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/site-packages/prometheus_client/exposition.py\", line 157, in _get_best_family\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     infos = socket.getaddrinfo(address, port)\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m   File \"/home/michael/anaconda3/envs/flow/lib/python3.7/socket.py\", line 748, in getaddrinfo\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\n",
      "\u001b[2m\u001b[33m(raylet)\u001b[0m socket.gaierror: [Errno -2] Name or service not known\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.44' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=117.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.44' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=117.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.63' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=153.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.63' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=153.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_20.4' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=154.50.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.98' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=225.50.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_20.6' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=226.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_00.97' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=225.50.\n",
      "\u001b[2m\u001b[36m(pid=2943)\u001b[0m Warning: Vehicle 'flow_20.6' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=226.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.135' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=297.50.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_20.8' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=298.50.\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.149' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=333.00.\n",
      "\u001b[2m\u001b[36m(pid=2946)\u001b[0m Warning: Vehicle 'flow_00.171' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=369.00.\n",
      "^C\n",
      "\u001b[2m\u001b[36m(pid=2948)\u001b[0m Warning: Vehicle 'flow_00.183' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=405.00.\n",
      "\u001b[2m\u001b[36m(pid=2947)\u001b[0m Warning: Vehicle 'flow_00.207' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=441.50.\n"
     ]
    }
   ],
   "source": [
    "!python examples/train.py merge0"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
