{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "6c260093",
   "metadata": {},
   "source": [
    "## Training Single Agent Ring Road"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40ee1510",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "%run ../../examples/train.py singleagent_ring"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a4c6143c",
   "metadata": {},
   "source": [
    "## Training Multiagent Ring Road"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cee41dfa",
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "%run ../../examples/train.py multiagent_ring"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0a6e1176",
   "metadata": {},
   "source": [
    "## Training Single Agent Figure 8"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ce197386",
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'num_workers': 5, 'num_envs_per_worker': 1, 'create_env_on_driver': False, 'rollout_fragment_length': 200, 'batch_mode': 'truncate_episodes', 'gamma': 0.999, 'lr': 5e-05, 'train_batch_size': 15000, 'model': {'_use_default_native_models': False, 'fcnet_hiddens': [3, 3], 'fcnet_activation': 'tanh', 'conv_filters': None, 'conv_activation': 'relu', 'post_fcnet_hiddens': [], 'post_fcnet_activation': 'relu', 'free_log_std': False, 'no_final_linear': False, 'vf_share_layers': False, 'use_lstm': False, 'max_seq_len': 20, 'lstm_cell_size': 256, 'lstm_use_prev_action': False, 'lstm_use_prev_reward': False, '_time_major': False, 'use_attention': False, 'attention_num_transformer_units': 1, 'attention_dim': 64, 'attention_num_heads': 1, 'attention_head_dim': 32, 'attention_memory_inference': 50, 'attention_memory_training': 50, 'attention_position_wise_mlp_dim': 32, 'attention_init_gru_gate_bias': 2.0, 'attention_use_n_prev_actions': 0, 'attention_use_n_prev_rewards': 0, 'num_framestacks': 'auto', 'dim': 84, 'grayscale': False, 'zero_mean': True, 'custom_model': None, 'custom_model_config': {}, 'custom_action_dist': None, 'custom_preprocessor': None, 'lstm_use_prev_action_reward': -1, 'framestack': True}, 'optimizer': {}, 'horizon': 1500, 'soft_horizon': False, 'no_done_at_end': False, 'env': None, 'observation_space': None, 'action_space': None, 'env_config': {}, 'env_task_fn': None, 'render_env': False, 'record_env': False, 'clip_rewards': None, 'normalize_actions': True, 'clip_actions': False, 'preprocessor_pref': 'deepmind', 'log_level': 'WARN', 'callbacks': <class 'ray.rllib.agents.callbacks.DefaultCallbacks'>, 'ignore_worker_failures': False, 'log_sys_usage': True, 'fake_sampler': False, 'framework': 'torch', 'eager_tracing': False, 'explore': True, 'exploration_config': {'type': 'StochasticSampling'}, 'evaluation_interval': None, 'evaluation_num_episodes': 10, 'evaluation_parallel_to_training': False, 'in_evaluation': False, 'evaluation_config': {}, 'evaluation_num_workers': 0, 'custom_eval_function': None, 'sample_async': False, 'sample_collector': <class 'ray.rllib.evaluation.collectors.simple_list_collector.SimpleListCollector'>, 'observation_filter': 'NoFilter', 'synchronize_filters': True, 'tf_session_args': {'intra_op_parallelism_threads': 2, 'inter_op_parallelism_threads': 2, 'gpu_options': {'allow_growth': True}, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'allow_soft_placement': True}, 'local_tf_session_args': {'intra_op_parallelism_threads': 8, 'inter_op_parallelism_threads': 8}, 'compress_observations': False, 'collect_metrics_timeout': 180, 'metrics_smoothing_episodes': 100, 'remote_worker_envs': False, 'remote_env_batch_wait_ms': 0, 'min_iter_time_s': 0, 'timesteps_per_iteration': 0, 'seed': None, 'extra_python_environs_for_driver': {}, 'extra_python_environs_for_worker': {}, 'num_gpus': 0, '_fake_gpus': False, 'num_cpus_per_worker': 1, 'num_gpus_per_worker': 0, 'custom_resources_per_worker': {}, 'num_cpus_for_driver': 1, 'placement_strategy': 'PACK', 'input': 'sampler', 'input_config': {}, 'actions_in_input_normalized': False, 'input_evaluation': ['is', 'wis'], 'postprocess_inputs': False, 'shuffle_buffer_size': 0, 'output': None, 'output_compress_columns': ['obs', 'new_obs'], 'output_max_file_size': 67108864, 'multiagent': {'policies': {}, 'policy_mapping_fn': None, 'policies_to_train': None, 'observation_fn': None, 'replay_mode': 'independent', 'count_steps_by': 'env_steps'}, 'logger_config': None, 'simple_optimizer': -1, 'monitor': -1, 'use_critic': True, 'use_gae': True, 'lambda': 0.97, 'kl_coeff': 0.2, 'sgd_minibatch_size': 128, 'shuffle_sequences': True, 'num_sgd_iter': 10, 'lr_schedule': None, 'vf_loss_coeff': 1.0, 'entropy_coeff': 0.0, 'entropy_coeff_schedule': None, 'clip_param': 0.3, 'vf_clip_param': 10.0, 'grad_clip': None, 'kl_target': 0.02, 'vf_share_layers': -1}\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-12 17:19:33,405\tINFO services.py:1247 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 4.9/31.2 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/11 CPUs, 0/11 GPUs, 0.0/10.1 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)<br>Result logdir: /home/michael-lab/ray_results/singleagent_figure_eight<br>Number of trials: 1/1 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td>PENDING </td><td>     </td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:35,402\tINFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:37,820\tWARNING util.py:55 -- Install gputil for GPU system monitoring.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m ring radius: 23.9\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m ring radius: 23.9\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m ring radius: 22.6\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24293)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24293)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24293)\u001b[0m ring radius: 28.8\n",
      "\u001b[2m\u001b[36m(pid=24293)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m ring radius: 29.9\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m  Retrying in 1 seconds\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m Could not connect to TraCI server at localhost:41241 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m Could not connect to TraCI server at localhost:34761 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m Could not connect to TraCI server at localhost:38545 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m Could not connect to TraCI server at localhost:59553 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m  Retrying in 2 seconds\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m Could not connect to TraCI server at localhost:41241 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24291)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m Could not connect to TraCI server at localhost:59553 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24288)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m Could not connect to TraCI server at localhost:34761 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24292)\u001b[0m  Retrying in 3 seconds\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m Could not connect to TraCI server at localhost:38545 [Errno 111] Connection refused\n",
      "\u001b[2m\u001b[36m(pid=24290)\u001b[0m  Retrying in 3 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-12 17:19:46,243\tERROR trial_runner.py:773 -- Trial PPO_AccelEnv-v0_1a6e3_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\", line 729, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py\", line 1564, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::PPO.train()\u001b[39m (pid=24294, ip=141.225.9.236)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 640, in train\n",
      "    raise e\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 629, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py\", line 170, in step\n",
      "    res = next(self.train_exec_impl)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 828, in add_wait_hooks\n",
      "    item = next(it)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24293, ip=141.225.9.236)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "    item = next(self.rollout_provider)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "    sample_collector=sample_collector,\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "    policy_id).transform(raw_obs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "    self.check_shape(observation)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "    observation, self._obs_space)\n",
      "ValueError: ('Observation ({}) outside given space ({})!', array([0.0396966 , 0.04231745, 0.05908949, 0.0851143 , 0.25556016,\n",
      "       0.45758481, 0.32095608, 0.03136504, 0.03968047, 0.35672162,\n",
      "       0.30305839, 0.06073966, 0.05070809, 0.046056  , 0.98200551,\n",
      "       0.01781315, 0.03975324, 0.06404648, 0.10018984, 0.26663414,\n",
      "       0.46881039, 0.54597901, 0.56653432, 0.66929871, 0.84483007,\n",
      "       0.91546522, 0.93819664, 0.96036757]), Box(3,))\n",
      "2023-04-12 17:19:46,245\tINFO trial_runner.py:1051 -- Trial PPO_AccelEnv-v0_1a6e3_00000: Attempting to restore trial state from last checkpoint.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.2/31.2 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/11 CPUs, 0/11 GPUs, 0.0/10.1 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 accelerator_type:G)<br>Result logdir: /home/michael-lab/ray_results/singleagent_figure_eight<br>Number of trials: 1/1 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td>PENDING </td><td>     </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                        </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td style=\"text-align: right;\">           1</td><td>/home/michael-lab/ray_results/singleagent_figure_eight/PPO_AccelEnv-v0_1a6e3_00000_0_2023-04-12_17-19-34/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:47,110\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24290, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.04801911, 0.02770424, 0.0443629 , 0.41935648, 0.47779532,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.48319521, 0.19890036, 0.11206531, 0.2677205 , 0.13345912,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.10699393, 0.09884455, 0.10248828, 0.08195512, 0.02702911,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.04753392, 0.06716615, 0.18718982, 0.26744282, 0.35978445,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.51579702, 0.55442147, 0.59428557, 0.88163695, 0.90875285,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.93399691, 0.95895182, 0.00457906]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:47,150\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24291, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.04015333, 0.04265723, 0.05893631, 0.08463743, 0.25535117,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.43012679, 0.19527785, 0.02080799, 0.04162917, 0.35960401,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.18350649, 0.05090052, 0.05081091, 0.04629604, 0.95605772,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.00673745, 0.03248002, 0.06105084, 0.10334324, 0.29455065,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.48142342, 0.53166301, 0.55511783, 0.66747371, 0.83273046,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.87856082, 0.90463831, 0.9306509 ]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:47,251\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24292, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.04373268, 0.0330736 , 0.0410742 , 0.13025599, 0.37785951,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.19329378, 0.05119448, 0.06336806, 0.06182747, 0.02540593,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.29784881, 0.29636205, 0.06284982, 0.05356373, 0.97788429,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.02301509, 0.04930083, 0.08026208, 0.235687  , 0.42189174,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.47406654, 0.50302885, 0.53261335, 0.56144274, 0.635191  ,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.83199571, 0.92099516, 0.94982454]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m 2023-04-12 17:19:47,315\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24288, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.05201299, 0.0363173 , 0.02711534, 0.07482049, 0.37443333,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.26136923, 0.04765148, 0.05272425, 0.07033759, 0.04680414,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.27361562, 0.3802847 , 0.1056561 , 0.0552745 , 0.        ,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.02343953, 0.04784314, 0.07267665, 0.20358584, 0.39934283,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.4679752 , 0.4942278 , 0.52115086, 0.55008135, 0.60366129,\n",
      "\u001b[2m\u001b[36m(pid=24294)\u001b[0m        0.792314  , 0.91367661, 0.94533116]), Box(3,))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:49,419\tINFO trainer.py:720 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:51,823\tWARNING util.py:55 -- Install gputil for GPU system monitoring.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24289)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24289)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24289)\u001b[0m ring radius: 21.6\n",
      "\u001b[2m\u001b[36m(pid=24289)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24286)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24286)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24286)\u001b[0m ring radius: 23.1\n",
      "\u001b[2m\u001b[36m(pid=24286)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24295)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24295)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24295)\u001b[0m ring radius: 24.3\n",
      "\u001b[2m\u001b[36m(pid=24295)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24287)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24287)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24287)\u001b[0m ring radius: 23.2\n",
      "\u001b[2m\u001b[36m(pid=24287)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24678)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24678)\u001b[0m -----------------------\n",
      "\u001b[2m\u001b[36m(pid=24678)\u001b[0m ring radius: 23.4\n",
      "\u001b[2m\u001b[36m(pid=24678)\u001b[0m -----------------------\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-12 17:19:55,383\tERROR trial_runner.py:773 -- Trial PPO_AccelEnv-v0_1a6e3_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trial_runner.py\", line 739, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py\", line 729, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/worker.py\", line 1564, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::PPO.train()\u001b[39m (pid=24296, ip=141.225.9.236)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 640, in train\n",
      "    raise e\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer.py\", line 629, in train\n",
      "    result = Trainable.train(self)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/tune/trainable.py\", line 237, in train\n",
      "    result = self.step()\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/agents/trainer_template.py\", line 170, in step\n",
      "    res = next(self.train_exec_impl)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 756, in __next__\n",
      "    return next(self.built_iterator)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 843, in apply_filter\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 876, in apply_flatten\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 828, in add_wait_hooks\n",
      "    item = next(it)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 783, in apply_foreach\n",
      "    for item in it:\n",
      "  [Previous line repeated 1 more time]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 471, in base_iterator\n",
      "    yield ray.get(futures, timeout=timeout)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/client_mode_hook.py\", line 82, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "ray.exceptions.RayTaskError(ValueError): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24678, ip=141.225.9.236)\n",
      "  File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "  File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "    return next(self.local_it)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "    yield self.sample()\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "    batches = [self.input_reader.next()]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "    batches = [self.get_data()]\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "    item = next(self.rollout_provider)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "    sample_collector=sample_collector,\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "    policy_id).transform(raw_obs)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "    self.check_shape(observation)\n",
      "  File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "    observation, self._obs_space)\n",
      "ValueError: ('Observation ({}) outside given space ({})!', array([0.04359881, 0.0324625 , 0.04204893, 0.12960655, 0.38133251,\n",
      "       0.21464249, 0.05220629, 0.06312984, 0.06219381, 0.02523491,\n",
      "       0.29902824, 0.32367924, 0.06994905, 0.05394874, 0.98111157,\n",
      "       0.02476225, 0.05016072, 0.08005322, 0.23048276, 0.42086643,\n",
      "       0.47728422, 0.50531161, 0.53389741, 0.56188064, 0.63346529,\n",
      "       0.82697258, 0.92541614, 0.95394041]), Box(3,))\n",
      "2023-04-12 17:19:55,384\tINFO trial_runner.py:1051 -- Trial PPO_AccelEnv-v0_1a6e3_00000: Attempting to restore trial state from last checkpoint.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 6.0/31.2 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/11 CPUs, 0/11 GPUs, 0.0/10.1 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 CPU_group_3_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/1.0 accelerator_type:G, 0.0/1.0 CPU_group_1_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/6.0 CPU_group_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/1.0 CPU_group_5_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/1.0 CPU_group_2_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/1.0 CPU_group_4_e6f321e66628a69e9387f1ac9e0c6df1, 0.0/1.0 CPU_group_0_e6f321e66628a69e9387f1ac9e0c6df1)<br>Result logdir: /home/michael-lab/ray_results/singleagent_figure_eight<br>Number of trials: 1/1 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td>PENDING </td><td>     </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                        </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td style=\"text-align: right;\">           2</td><td>/home/michael-lab/ray_results/singleagent_figure_eight/PPO_AccelEnv-v0_1a6e3_00000_0_2023-04-12_17-19-34/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:55,412\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24289, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.05466018, 0.04026042, 0.02322941, 0.05172639, 0.35653264,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.20943727, 0.0429006 , 0.049281  , 0.06832074, 0.05479547,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.27200891, 0.30460175, 0.06343293, 0.05372467, 0.96939076,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.01771468, 0.04532665, 0.07207254, 0.21027533, 0.4067631 ,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.46568543, 0.49467081, 0.52444209, 0.55735343, 0.61332933,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.81191059, 0.90945825, 0.93959992]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:55,416\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24287, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.04197141, 0.03225614, 0.04410317, 0.13797896, 0.38479975,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.20465664, 0.05129661, 0.06304318, 0.05903116, 0.0235716 ,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.29903563, 0.3074938 , 0.06704814, 0.05303064, 0.98085561,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.02472939, 0.05039404, 0.08135358, 0.23789744, 0.42318119,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.47714332, 0.50537277, 0.53418449, 0.56194392, 0.63642112,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.83423153, 0.92512547, 0.95360184]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:55,431\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24286, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([0.03954529, 0.05512647, 0.08689365, 0.24912892, 0.36148602,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.07304874, 0.05297887, 0.05514379, 0.04696721, 0.02596906,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.03471183, 0.35464198, 0.25685666, 0.03782664, 0.00429318,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.0310304 , 0.0607304 , 0.10318732, 0.29433445, 0.4275444 ,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.45665884, 0.48425596, 0.51262184, 0.53922638, 0.56408185,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        0.68609192, 0.88710551, 0.96044409]), Box(3,))\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m 2023-04-12 17:19:55,470\tERROR worker.py:79 -- Unhandled error (suppress with RAY_IGNORE_UNHANDLED_ERRORS=1): \u001b[36mray::RolloutWorker.par_iter_next()\u001b[39m (pid=24295, ip=141.225.9.236)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 534, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"python/ray/_raylet.pyx\", line 484, in ray._raylet.execute_task.function_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/_private/function_manager.py\", line 563, in actor_method_executor\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/util/iter.py\", line 1151, in par_iter_next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     return next(self.local_it)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 338, in gen_rollouts\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     yield self.sample()\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/rollout_worker.py\", line 739, in sample\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.input_reader.next()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 101, in next\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     batches = [self.get_data()]\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 231, in get_data\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     item = next(self.rollout_provider)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 615, in _env_runner\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     sample_collector=sample_collector,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/evaluation/sampler.py\", line 821, in _process_observations\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     policy_id).transform(raw_obs)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 187, in transform\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     self.check_shape(observation)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m   File \"/home/michael-lab/miniconda3/envs/flow/lib/python3.7/site-packages/ray/rllib/models/preprocessors.py\", line 68, in check_shape\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m     observation, self._obs_space)\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m ValueError: ('Observation ({}) outside given space ({})!', array([5.57767433e-02, 6.41271601e-02, 4.97741383e-02, 1.75002657e-06,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        3.24048136e-01, 3.86450676e-01, 8.95325810e-02, 4.22550143e-02,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        7.17077566e-02, 2.15163869e-01, 3.72351101e-01, 1.11270390e-01,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        4.40508124e-02, 4.58974822e-02, 9.73836653e-01, 1.77234839e-02,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        4.51075444e-02, 7.04462756e-02, 1.56334030e-01, 3.71256374e-01,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        4.93017900e-01, 5.22967451e-01, 5.49180361e-01, 5.88289298e-01,\n",
      "\u001b[2m\u001b[36m(pid=24296)\u001b[0m        7.54636834e-01, 8.89673453e-01, 9.22331925e-01, 9.47845560e-01]), Box(3,))\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-12 17:19:57,458\tWARNING tune.py:508 -- SIGINT received (e.g. via Ctrl+C), ending Ray Tune run. This will try to checkpoint the experiment state one last time. Press CTRL+C one more time (or send SIGINT/SIGKILL/SIGTERM) to skip. \n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 4.5/31.2 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/11 CPUs, 0/11 GPUs, 0.0/10.1 GiB heap, 0.0/14.65 GiB objects (0.0/1.0 CPU_group_2_45206f47c340246e2d88787a4e6d2b7a, 0.0/6.0 CPU_group_45206f47c340246e2d88787a4e6d2b7a, 0.0/1.0 CPU_group_5_45206f47c340246e2d88787a4e6d2b7a, 0.0/1.0 accelerator_type:G, 0.0/1.0 CPU_group_4_45206f47c340246e2d88787a4e6d2b7a, 0.0/1.0 CPU_group_0_45206f47c340246e2d88787a4e6d2b7a, 0.0/1.0 CPU_group_1_45206f47c340246e2d88787a4e6d2b7a, 0.0/1.0 CPU_group_3_45206f47c340246e2d88787a4e6d2b7a)<br>Result logdir: /home/michael-lab/ray_results/singleagent_figure_eight<br>Number of trials: 1/1 (1 PENDING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th>status  </th><th>loc  </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td>PENDING </td><td>     </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 1<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name                 </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                        </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>PPO_AccelEnv-v0_1a6e3_00000</td><td style=\"text-align: right;\">           2</td><td>/home/michael-lab/ray_results/singleagent_figure_eight/PPO_AccelEnv-v0_1a6e3_00000_0_2023-04-12_17-19-34/error.txt</td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-12 17:19:57,672\tERROR tune.py:546 -- Trials did not complete: [PPO_AccelEnv-v0_1a6e3_00000]\n",
      "2023-04-12 17:19:57,673\tINFO tune.py:550 -- Total run time: 23.60 seconds (23.35 seconds for the tuning loop).\n",
      "2023-04-12 17:19:57,674\tWARNING tune.py:555 -- Experiment has been interrupted, but the most recent state was saved. You can continue running this experiment by passing `resume=True` to `tune.run()`\n"
     ]
    }
   ],
   "source": [
    "%run ../../examples/train.py singleagent_figure_eight"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e61a7b2a",
   "metadata": {},
   "source": [
    "## Training Intersection Network"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b1789eb3",
   "metadata": {},
   "outputs": [],
   "source": [
    "%run ../../examples/train.py intersection"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "51244303",
   "metadata": {},
   "source": [
    "## Training Bottleneck"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e6692bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "%run ../../examples/train.py bottleneck0"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7fb5d45a",
   "metadata": {},
   "source": [
    "## Training Merge Network"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "08a6cf15",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "%run ../../examples/train.py merge0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "376dbf4d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
